yatube/api/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework import routers

from .views import CommentViewSet, FollowViewSet, GroupViewSet, PostViewSet

app_name = 'api'

router_v1 = routers.DefaultRouter()
router_v1.register(r'groups', GroupViewSet, basename='groups')
router_v1.register(r'posts', PostViewSet, basename='posts')
router_v1.register(
    r'posts/(?P<post_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)
router_v1.register(r'follow', FollowViewSet, basename='follow')

urlpatterns = [
    path(r'v1/', include(router_v1.urls)),
    path(r'v1/', include('djoser.urls.jwt')),
    path(
        r'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    )
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('user_change/', views.user_change, name='user_change'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

yatube/templates/includes/comments.html
<ul class="list-group list-group-flush">
  {% for comment in comments %}
    <li class="list-group-item">
      <div class="media mb-0">
        <div class="media-body">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.get_name }}
          </a>
          {{ comment.created|date:"d E Y H:i:s" }}
          <p>
            {{ comment.text|linebreaksbr }}
          </p>
        </div>
      </div>
    </li>
  {% endfor %}
</ul>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:roadmap' %}active{% endif %}"
             href="{% url 'about:roadmap' %}">Дорожная карта</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
             href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
             href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
            href="{% url 'users:user_change' %}">{{ user.get_name }}
          </a>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}