yatube/api/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework import routers

from .views import CommentViewSet, FollowViewSet, GroupViewSet, PostViewSet

app_name = 'api'

router_v1 = routers.DefaultRouter()
router_v1.register(r'groups', GroupViewSet, basename='groups')
router_v1.register(r'posts', PostViewSet, basename='posts')
router_v1.register(
    r'posts/(?P<post_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)
router_v1.register(r'follow', FollowViewSet, basename='follow')

urlpatterns = [
    path(r'v1/', include(router_v1.urls)),
    path(r'v1/', include('djoser.urls.jwt')),
    path(
        r'redoc/',
        TemplateView.as_view(template_name='redoc.html'),
        name='redoc'
    )
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models
from pytils.translit import slugify

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Имя',
        help_text='Введите имя сообщества',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Адрес',
        help_text='Введите адрес (код) сообщества',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Введите описание сообщества',
    )

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self) -> str:
        return str(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст нового поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выберите из списка автора публикации',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу, к которой будет относиться пост',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name='Картинка',
        help_text='Выберите картинку',
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Выберите пост, к которому относится комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Выберите из списка автора комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Выберите из списка подписчика',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Following',
        help_text='Выберите из списка пользователя, на которого подписываются',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name='unique_follow',
                fields=['user', 'author'],
            ),
            models.CheckConstraint(
                name='prevent_self_follow',
                check=~models.Q(user=models.F('author'))
            ),
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['rows'] = 5


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['rows'] = 3

yatube/posts/views.py
from core.utils import get_page_obj
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def index(request):
    post_list = Post.objects.select_related(
        'author', 'group'
    ).all().annotate(comments_count=Count('comments'))
    context = {
        'page_obj': get_page_obj(request, post_list),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all().annotate(
        comments_count=Count('comments')
    )
    context = {
        'page_obj': get_page_obj(request, post_list),
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    posts = Post.objects.select_related(
        'author', 'group'
    ).filter(author=author).all().annotate(
        comments_count=Count('comments'),
    )
    posts_count = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    context = {
        'page_obj': get_page_obj(request, posts),
        'posts_count': posts_count,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        id=post_id
    )
    posts_count = Post.objects.filter(author=post.author).count()
    comment_form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('author').filter(
        post=post).all()
    context = {
        'post': post,
        'posts_count': posts_count,
        'form': comment_form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related(
        'author', 'group'
    ).filter(author__following__user=request.user).all().annotate(
        comments_count=Count('comments')
    )
    context = {
        'page_obj': get_page_obj(request, post_list),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if not author == request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}             
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %} 
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data" action=
            {% if is_edit %}
              "{% url 'posts:post_edit' form.instance.id %}"
            {% else %}
              "{% url 'posts:post_create' %}"
            {% endif %}
          >
          {% csrf_token %}
            
          {% for field in form %}
            <div class="form-group row my-3 p-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% block title %}
  Последние обновления избранных авторов
{% endblock %}
{% block content %}
  {% with follow=True %}
    {% include 'posts/includes/switcher.html' %}
  {% endwith %}
  <h1>Последние обновления избранных авторов</h1>
  {% for post in page_obj %}
    {% include 'posts/includes/post_article.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaksbr }}</p>
  {% with is_group_list=True %}
    {% for post in page_obj %}
        {% include 'posts/includes/post_article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'includes/paginator.html' %}
  {% endwith %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% with index=True %}
    {% include 'posts/includes/switcher.html' %}
  {% endwith %}
  <h1>Последние обновления на сайте</h1>
  {% cache 20 index_page page_obj %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_article.html' %}
      {% comment %} {% if not forloop.last %}<hr>{% endif %} {% endcomment %}
    {% endfor %} 
    {% include 'includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Автор: 
          <span >
            <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.get_name }}
            </a>
          </span>
        </li>
        {% if post.group %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Группа: 
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group.title }}
            </a>
          </li>
        {% endif %}  
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Дата публикации: <span >{{ post.created|date:"d E Y" }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ posts_count }}</span>
        </li>
      </ul>
    </aside>
    <article class="border border-primary rounded col-12 col-md-9">
      {% thumbnail post.image "x300" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}         

      {% load user_filters %}
      
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% include 'includes/comments.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}
  Профайл пользователя {{ author.get_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_name }}</h1>
    <h3>Всего постов: {{ posts_count }}</h3>
    {% if user.is_authenticated and user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% with is_profile=True %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'includes/paginator.html' %}
  {% endwith %}
{% endblock %}